services:
  express-app:
    image: hinichijou/devopswithdocker3-1:latest
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: hinichijou/devopswithdocker3-1
    container_name: watchtower